drop database equipamento
CREATE DATABASE EQUIPAMENTO
USE EQUIPAMENTO
CREATE TABLE TIPO_EQUIPAMENTO
(
  ID_TIPO_EQUIPAMENTO INT NOT NULL IDENTITY,
  DESIGNACAO VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_TIPO_EQUIPAMENTO)
);

CREATE TABLE EQUIPAMENTO
(
  ID_EQUIPAMENTO INT NOT NULL IDENTITY,
  DESIGNACAO_EQUIPAMENTO VARCHAR(50) NOT NULL,
  DATA_REGISTO DATE NOT NULL,
  ESTADO_EQUIPAMENTO TINYINT NOT NULL,
  OBSERVACOES VARCHAR(512) NOT NULL,
  ID_TIPO_EQUIPAMENTO INT NOT NULL,
  PRIMARY KEY (ID_EQUIPAMENTO),
  FOREIGN KEY (ID_TIPO_EQUIPAMENTO) REFERENCES Tipo_equipamento(ID_TIPO_EQUIPAMENTO)
);